version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: hakabonqfront
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: hakabonqback
    command: npm start
    ports:
      - 8080:8080
